### ISSUE TITLE
Does not support more than one remote_pin_service

### ISSUE THREAD

**Issue by gonzalob** [mborho/terraform-provider-ipfs#3]
Documentation states it should support many, however there's an explicit restriction on https://github.com/mborho/terraform-provider-ipfs/blob/a0e8c871115065273501a691dba7224d39b47605/provider.go#L21

**Comment by mborho** [comment]
Your're right, thanks for reporting!

Fix for this will be coming in the next days.

**Comment by mborho** [comment]
Hi, thanks for reporting!

Hmm, after some investigation it looks like it works anyways with following provider definition:

```
provider "ipfs" {
  remote_pin_service {
    name     = "dev"
    endpoint = "http://localhost:5000/api/v1"
    token    = "token1"
  }

  remote_pin_service {
    name     = "dev2"
    endpoint = "http://localhost:5010/api/v1"
    token    = "token1"
  }
}

resource "ipfs_remote_pin" "demo" {
  service = "dev"
  [...]
}

resource "ipfs_remote_pin" "demo2" {
  service = "dev2"
  [...]
}
```

Did you get an error message or something?

**Comment by mborho** [comment]
Sorry, I was working at 0.xx version of terraform. Now I see the error too.

**Comment by gonzalob** [comment]
I'm sorry for missing your updates! I didn't get notifications :-(

It's working great now. Thanks a lot!
